# Generated by Django 6.0 on 2026-03-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Products',
            field=models.ManyToManyField(through='store.OrderItem', to='store.product'),
        ),
    ]
