# Generated by Django 6.0 on 2026-03-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Products',
        ),
    ]
